// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADd1FmKvrRWId5gXYWeVzAXaoLoM82pc',
    appId: '1:539116682354:web:41f5a9c0aa3f798c3696eb',
    messagingSenderId: '539116682354',
    projectId: 'mobile-learning-skripsi',
    authDomain: 'mobile-learning-skripsi.firebaseapp.com',
    storageBucket: 'mobile-learning-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATyXEAE80GYbMbWkzGzQ-X7_orvRJOP3c',
    appId: '1:539116682354:android:2390887d5f3717bd3696eb',
    messagingSenderId: '539116682354',
    projectId: 'mobile-learning-skripsi',
    storageBucket: 'mobile-learning-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRb4TuqbBreuGl24wZw2PPEBgd23SSnA',
    appId: '1:539116682354:ios:48f63daaf30cf8983696eb',
    messagingSenderId: '539116682354',
    projectId: 'mobile-learning-skripsi',
    storageBucket: 'mobile-learning-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.mlix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRb4TuqbBreuGl24wZw2PPEBgd23SSnA',
    appId: '1:539116682354:ios:48f63daaf30cf8983696eb',
    messagingSenderId: '539116682354',
    projectId: 'mobile-learning-skripsi',
    storageBucket: 'mobile-learning-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.mlix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAADd1FmKvrRWId5gXYWeVzAXaoLoM82pc',
    appId: '1:539116682354:web:ed9ec4121551633c3696eb',
    messagingSenderId: '539116682354',
    projectId: 'mobile-learning-skripsi',
    authDomain: 'mobile-learning-skripsi.firebaseapp.com',
    storageBucket: 'mobile-learning-skripsi.firebasestorage.app',
  );
}
